import type { ComponentDefinition } from "./types";

export const COMPONENT_CATALOG: ComponentDefinition[] = [
  // Clients
  {
    type: "mobile_client",
    label: "Mobile Client",
    category: "client",
    description: "iOS/Android app used by end users",
    color: "#38bdf8",
    icon: "smartphone",
    attributes: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: ["iOS", "Android", "Cross-platform"],
        defaultValue: "Cross-platform",
      },
      {
        key: "network",
        label: "Network",
        type: "select",
        options: ["4G", "5G", "WiFi", "Mixed"],
        defaultValue: "Mixed",
      },
      {
        key: "offlineSupport",
        label: "Offline support",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "web_client",
    label: "Web Client",
    category: "client",
    description: "Browser-based web application",
    color: "#38bdf8",
    icon: "monitor",
    attributes: [
      {
        key: "device",
        label: "Primary device",
        type: "select",
        options: ["Desktop", "Mobile", "Both"],
        defaultValue: "Both",
      },
      {
        key: "rendering",
        label: "Rendering",
        type: "select",
        options: ["CSR", "SSR", "SSG", "Hybrid"],
        defaultValue: "SSR",
      },
    ],
  },
  {
    type: "iot_device",
    label: "IoT Device",
    category: "client",
    description: "Sensor, camera, or embedded device",
    color: "#38bdf8",
    icon: "cpu",
    attributes: [
      {
        key: "protocol",
        label: "Protocol",
        type: "select",
        options: ["MQTT", "HTTP", "CoAP", "WebSocket"],
        defaultValue: "MQTT",
      },
      {
        key: "bandwidth",
        label: "Bandwidth",
        type: "select",
        options: ["Low", "Medium", "High"],
        defaultValue: "Low",
      },
    ],
  },

  // Edge
  {
    type: "dns",
    label: "DNS",
    category: "edge",
    description: "Domain name resolution and routing",
    color: "#a78bfa",
    icon: "globe",
    attributes: [
      {
        key: "routing",
        label: "Routing policy",
        type: "select",
        options: ["Simple", "Latency-based", "Geo", "Weighted"],
        defaultValue: "Latency-based",
      },
      {
        key: "ttlSeconds",
        label: "TTL",
        type: "number",
        min: 1,
        max: 86400,
        unit: "s",
        defaultValue: 60,
      },
    ],
  },
  {
    type: "cdn",
    label: "CDN",
    category: "edge",
    description: "Edge cache for static and dynamic content",
    color: "#a78bfa",
    icon: "globe-2",
    attributes: [
      {
        key: "regions",
        label: "Edge regions",
        type: "select",
        options: ["Single", "Multi-region", "Global"],
        defaultValue: "Global",
      },
      {
        key: "cacheTtl",
        label: "Cache TTL",
        type: "number",
        min: 0,
        max: 86400,
        unit: "s",
        defaultValue: 300,
      },
      {
        key: "httpsOnly",
        label: "HTTPS only",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "api_gateway",
    label: "API Gateway",
    category: "edge",
    description: "Entry point for APIs: routing, auth, throttling",
    color: "#a78bfa",
    icon: "door-open",
    attributes: [
      {
        key: "auth",
        label: "Auth",
        type: "select",
        options: ["None", "API Key", "JWT", "OAuth2"],
        defaultValue: "JWT",
      },
      {
        key: "rateLimitRps",
        label: "Rate limit",
        type: "number",
        min: 1,
        max: 1000000,
        unit: "rps",
        defaultValue: 1000,
      },
      {
        key: "timeoutMs",
        label: "Timeout",
        type: "number",
        min: 50,
        max: 60000,
        unit: "ms",
        defaultValue: 3000,
      },
    ],
  },
  {
    type: "load_balancer",
    label: "Load Balancer",
    category: "edge",
    description: "Distributes traffic across backends",
    color: "#a78bfa",
    icon: "scale",
    attributes: [
      {
        key: "layer",
        label: "Layer",
        type: "select",
        options: ["L4", "L7"],
        defaultValue: "L7",
      },
      {
        key: "algorithm",
        label: "Algorithm",
        type: "select",
        options: ["Round robin", "Least connections", "IP hash", "Weighted"],
        defaultValue: "Least connections",
      },
      {
        key: "healthChecks",
        label: "Health checks",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "multiAz",
        label: "Multi-AZ",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "rate_limiter",
    label: "Rate Limiter",
    category: "edge",
    description: "Protects services from overload and abuse",
    color: "#a78bfa",
    icon: "gauge",
    attributes: [
      {
        key: "strategy",
        label: "Strategy",
        type: "select",
        options: ["Token bucket", "Sliding window", "Fixed window", "Leaky bucket"],
        defaultValue: "Token bucket",
      },
      {
        key: "limitRps",
        label: "Limit",
        type: "number",
        min: 1,
        max: 1000000,
        unit: "rps",
        defaultValue: 100,
      },
      {
        key: "scope",
        label: "Scope",
        type: "select",
        options: ["Per IP", "Per user", "Global", "Per API key"],
        defaultValue: "Per user",
      },
    ],
  },
  {
    type: "waf",
    label: "WAF",
    category: "edge",
    description: "Web application firewall",
    color: "#a78bfa",
    icon: "shield",
    attributes: [
      {
        key: "mode",
        label: "Mode",
        type: "select",
        options: ["Detect", "Block"],
        defaultValue: "Block",
      },
      {
        key: "ddosProtection",
        label: "DDoS protection",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },

  // Compute
  {
    type: "app_server",
    label: "App Server",
    category: "compute",
    description: "Stateful or stateless application servers",
    color: "#34d399",
    icon: "server",
    attributes: [
      {
        key: "stateless",
        label: "Stateless",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 3,
      },
      {
        key: "autoScale",
        label: "Auto-scale",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "region",
        label: "Region strategy",
        type: "select",
        options: ["Single AZ", "Multi-AZ", "Multi-region"],
        defaultValue: "Multi-AZ",
      },
    ],
  },
  {
    type: "microservice",
    label: "Microservice",
    category: "compute",
    description: "Focused service for a domain capability",
    color: "#34d399",
    icon: "boxes",
    attributes: [
      {
        key: "name",
        label: "Service name",
        type: "text",
        defaultValue: "service",
      },
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 3,
      },
      {
        key: "timeoutMs",
        label: "Timeout",
        type: "number",
        min: 50,
        max: 60000,
        unit: "ms",
        defaultValue: 2000,
      },
    ],
  },
  {
    type: "serverless",
    label: "Serverless Function",
    category: "compute",
    description: "Event-driven function compute",
    color: "#34d399",
    icon: "zap",
    attributes: [
      {
        key: "runtime",
        label: "Runtime",
        type: "select",
        options: ["Node", "Python", "Go", "Java", "Other"],
        defaultValue: "Node",
      },
      {
        key: "memoryMb",
        label: "Memory",
        type: "number",
        min: 128,
        max: 10240,
        unit: "MB",
        defaultValue: 512,
      },
      {
        key: "timeoutMs",
        label: "Timeout",
        type: "number",
        min: 100,
        max: 900000,
        unit: "ms",
        defaultValue: 10000,
      },
      {
        key: "concurrency",
        label: "Max concurrency",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 100,
      },
    ],
  },
  {
    type: "worker",
    label: "Background Worker",
    category: "compute",
    description: "Async job processor / consumer",
    color: "#34d399",
    icon: "cog",
    attributes: [
      {
        key: "concurrency",
        label: "Concurrency",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 10,
      },
      {
        key: "retryPolicy",
        label: "Retries",
        type: "select",
        options: ["None", "3x", "5x", "Exponential backoff"],
        defaultValue: "Exponential backoff",
      },
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 2,
      },
    ],
  },
  {
    type: "batch_job",
    label: "Batch Job",
    category: "compute",
    description: "Scheduled or on-demand batch processing",
    color: "#34d399",
    icon: "calendar",
    attributes: [
      {
        key: "schedule",
        label: "Schedule",
        type: "select",
        options: ["On-demand", "Hourly", "Daily", "Weekly"],
        defaultValue: "Daily",
      },
      {
        key: "parallelism",
        label: "Parallelism",
        type: "number",
        min: 1,
        max: 1000,
        defaultValue: 4,
      },
    ],
  },

  // Data
  {
    type: "sql_database",
    label: "SQL Database",
    category: "data",
    description: "Relational database (Postgres, MySQL, etc.)",
    color: "#fbbf24",
    icon: "database",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["PostgreSQL", "MySQL", "SQL Server", "CockroachDB"],
        defaultValue: "PostgreSQL",
      },
      {
        key: "sizeGb",
        label: "Storage size",
        type: "number",
        min: 1,
        max: 1000000,
        unit: "GB",
        defaultValue: 100,
      },
      {
        key: "replication",
        label: "Replication",
        type: "select",
        options: ["None", "Async replicas", "Sync multi-AZ", "Multi-region"],
        defaultValue: "Async replicas",
      },
      {
        key: "sharding",
        label: "Sharding",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "readReplicas",
        label: "Read replicas",
        type: "number",
        min: 0,
        max: 100,
        defaultValue: 1,
      },
    ],
  },
  {
    type: "nosql_database",
    label: "NoSQL Database",
    category: "data",
    description: "Document, key-value, or wide-column store",
    color: "#fbbf24",
    icon: "database",
    attributes: [
      {
        key: "model",
        label: "Data model",
        type: "select",
        options: ["Document", "Key-value", "Wide-column", "Graph"],
        defaultValue: "Document",
      },
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["DynamoDB", "MongoDB", "Cassandra", "Redis", "Firestore", "Neo4j"],
        defaultValue: "DynamoDB",
      },
      {
        key: "sizeGb",
        label: "Storage size",
        type: "number",
        min: 1,
        max: 10000000,
        unit: "GB",
        defaultValue: 500,
      },
      {
        key: "consistency",
        label: "Consistency",
        type: "select",
        options: ["Eventual", "Strong", "Bounded staleness", "Session"],
        defaultValue: "Eventual",
      },
      {
        key: "partitioning",
        label: "Partitioning",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "cache",
    label: "Cache",
    category: "data",
    description: "In-memory cache for low-latency reads",
    color: "#fbbf24",
    icon: "layers",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["Redis", "Memcached", "CDN cache", "Application cache"],
        defaultValue: "Redis",
      },
      {
        key: "sizeGb",
        label: "Memory size",
        type: "number",
        min: 1,
        max: 10000,
        unit: "GB",
        defaultValue: 16,
      },
      {
        key: "ttlSeconds",
        label: "Default TTL",
        type: "number",
        min: 1,
        max: 86400,
        unit: "s",
        defaultValue: 300,
      },
      {
        key: "eviction",
        label: "Eviction",
        type: "select",
        options: ["LRU", "LFU", "TTL", "No eviction"],
        defaultValue: "LRU",
      },
      {
        key: "clustered",
        label: "Clustered",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "search_index",
    label: "Search Index",
    category: "data",
    description: "Full-text or vector search engine",
    color: "#fbbf24",
    icon: "search",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["Elasticsearch", "OpenSearch", "Algolia", "Typesense", "Vector DB"],
        defaultValue: "Elasticsearch",
      },
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 0,
        max: 20,
        defaultValue: 1,
      },
      {
        key: "shards",
        label: "Shards",
        type: "number",
        min: 1,
        max: 1000,
        defaultValue: 3,
      },
    ],
  },
  {
    type: "time_series_db",
    label: "Time-Series DB",
    category: "data",
    description: "Metrics and high-volume time series storage",
    color: "#fbbf24",
    icon: "activity",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["InfluxDB", "TimescaleDB", "Prometheus", "CloudWatch"],
        defaultValue: "TimescaleDB",
      },
      {
        key: "retentionDays",
        label: "Retention",
        type: "number",
        min: 1,
        max: 3650,
        unit: "days",
        defaultValue: 30,
      },
    ],
  },
  {
    type: "data_warehouse",
    label: "Data Warehouse",
    category: "data",
    description: "Analytics and OLAP warehouse",
    color: "#fbbf24",
    icon: "building-2",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["Snowflake", "BigQuery", "Redshift", "ClickHouse"],
        defaultValue: "BigQuery",
      },
      {
        key: "sizeTb",
        label: "Data size",
        type: "number",
        min: 1,
        max: 100000,
        unit: "TB",
        defaultValue: 10,
      },
    ],
  },

  // Storage
  {
    type: "object_storage",
    label: "Object Storage",
    category: "storage",
    description: "Blob/object store for media and files",
    color: "#fb923c",
    icon: "hard-drive",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["S3", "GCS", "Azure Blob", "MinIO"],
        defaultValue: "S3",
      },
      {
        key: "sizeTb",
        label: "Capacity",
        type: "number",
        min: 1,
        max: 1000000,
        unit: "TB",
        defaultValue: 50,
      },
      {
        key: "durability",
        label: "Durability",
        type: "select",
        options: ["11 nines", "99.999999999%", "Regional", "Cross-region"],
        defaultValue: "11 nines",
      },
      {
        key: "replication",
        label: "Replication",
        type: "select",
        options: ["Single region", "Cross-region", "Multi-region"],
        defaultValue: "Cross-region",
      },
    ],
  },
  {
    type: "block_storage",
    label: "Block Storage",
    category: "storage",
    description: "Persistent block volumes for VMs/containers",
    color: "#fb923c",
    icon: "disc",
    attributes: [
      {
        key: "iops",
        label: "IOPS",
        type: "number",
        min: 100,
        max: 1000000,
        defaultValue: 3000,
      },
      {
        key: "sizeGb",
        label: "Size",
        type: "number",
        min: 1,
        max: 100000,
        unit: "GB",
        defaultValue: 500,
      },
      {
        key: "replicated",
        label: "Replicated",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },

  // Messaging
  {
    type: "message_queue",
    label: "Message Queue",
    category: "messaging",
    description: "Point-to-point async messaging",
    color: "#f472b6",
    icon: "list-ordered",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["SQS", "RabbitMQ", "ActiveMQ", "Azure Queue"],
        defaultValue: "SQS",
      },
      {
        key: "delivery",
        label: "Delivery",
        type: "select",
        options: ["At-least-once", "Exactly-once", "At-most-once"],
        defaultValue: "At-least-once",
      },
      {
        key: "dlq",
        label: "Dead-letter queue",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "visibilityTimeoutSec",
        label: "Visibility timeout",
        type: "number",
        min: 1,
        max: 43200,
        unit: "s",
        defaultValue: 30,
      },
    ],
  },
  {
    type: "pubsub",
    label: "Pub/Sub",
    category: "messaging",
    description: "Publish-subscribe event fan-out",
    color: "#f472b6",
    icon: "radio",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["SNS", "Google Pub/Sub", "Redis Pub/Sub", "NATS"],
        defaultValue: "SNS",
      },
      {
        key: "fanout",
        label: "Fan-out style",
        type: "select",
        options: ["Push", "Pull", "Both"],
        defaultValue: "Push",
      },
      {
        key: "ordering",
        label: "Message ordering",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "stream_processor",
    label: "Stream Processor",
    category: "messaging",
    description: "Real-time event streaming platform",
    color: "#f472b6",
    icon: "waves",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["Kafka", "Kinesis", "Pulsar", "Redpanda"],
        defaultValue: "Kafka",
      },
      {
        key: "partitions",
        label: "Partitions",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 12,
      },
      {
        key: "retentionHours",
        label: "Retention",
        type: "number",
        min: 1,
        max: 8760,
        unit: "h",
        defaultValue: 168,
      },
      {
        key: "replicationFactor",
        label: "Replication factor",
        type: "number",
        min: 1,
        max: 10,
        defaultValue: 3,
      },
    ],
  },
  {
    type: "event_bus",
    label: "Event Bus",
    category: "messaging",
    description: "Domain event backbone for services",
    color: "#f472b6",
    icon: "git-branch",
    attributes: [
      {
        key: "style",
        label: "Style",
        type: "select",
        options: ["Choreography", "Orchestration", "Hybrid"],
        defaultValue: "Choreography",
      },
      {
        key: "schemaRegistry",
        label: "Schema registry",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },

  // Security
  {
    type: "auth_service",
    label: "Auth Service",
    category: "security",
    description: "Authentication and session management",
    color: "#ef4444",
    icon: "key",
    attributes: [
      {
        key: "methods",
        label: "Methods",
        type: "select",
        options: ["Password", "OAuth/OIDC", "SSO", "Passwordless", "MFA"],
        defaultValue: "OAuth/OIDC",
      },
      {
        key: "tokenTtlMin",
        label: "Token TTL",
        type: "number",
        min: 1,
        max: 10080,
        unit: "min",
        defaultValue: 60,
      },
      {
        key: "mfa",
        label: "MFA required",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "identity_provider",
    label: "Identity Provider",
    category: "security",
    description: "External IdP / SSO provider",
    color: "#ef4444",
    icon: "fingerprint",
    attributes: [
      {
        key: "protocol",
        label: "Protocol",
        type: "select",
        options: ["OIDC", "SAML", "LDAP"],
        defaultValue: "OIDC",
      },
      {
        key: "provider",
        label: "Provider",
        type: "select",
        options: ["Auth0", "Okta", "Cognito", "Azure AD", "Custom"],
        defaultValue: "Cognito",
      },
    ],
  },
  {
    type: "secrets_manager",
    label: "Secrets Manager",
    category: "security",
    description: "Secure storage for keys and secrets",
    color: "#ef4444",
    icon: "lock",
    attributes: [
      {
        key: "rotation",
        label: "Auto-rotation",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["AWS Secrets Manager", "Vault", "GCP Secret Manager"],
        defaultValue: "Vault",
      },
    ],
  },

  // Observability
  {
    type: "monitoring",
    label: "Monitoring",
    category: "observability",
    description: "Metrics, alerts, and dashboards",
    color: "#94a3b8",
    icon: "bar-chart-3",
    attributes: [
      {
        key: "stack",
        label: "Stack",
        type: "select",
        options: ["Prometheus+Grafana", "Datadog", "CloudWatch", "New Relic"],
        defaultValue: "Prometheus+Grafana",
      },
      {
        key: "alerting",
        label: "Alerting",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "logging",
    label: "Logging",
    category: "observability",
    description: "Centralized log aggregation",
    color: "#94a3b8",
    icon: "scroll-text",
    attributes: [
      {
        key: "stack",
        label: "Stack",
        type: "select",
        options: ["ELK", "Loki", "CloudWatch Logs", "Datadog"],
        defaultValue: "ELK",
      },
      {
        key: "retentionDays",
        label: "Retention",
        type: "number",
        min: 1,
        max: 3650,
        unit: "days",
        defaultValue: 30,
      },
    ],
  },
  {
    type: "tracing",
    label: "Distributed Tracing",
    category: "observability",
    description: "Request traces across services",
    color: "#94a3b8",
    icon: "git-merge",
    attributes: [
      {
        key: "stack",
        label: "Stack",
        type: "select",
        options: ["OpenTelemetry", "Jaeger", "Zipkin", "X-Ray"],
        defaultValue: "OpenTelemetry",
      },
      {
        key: "sampleRate",
        label: "Sample rate %",
        type: "number",
        min: 1,
        max: 100,
        unit: "%",
        defaultValue: 10,
      },
    ],
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  client: "Clients",
  edge: "Edge & Networking",
  compute: "Compute",
  data: "Data Stores",
  storage: "Storage",
  messaging: "Messaging & Streaming",
  security: "Security & Identity",
  observability: "Observability",
};

export const CATEGORY_ORDER = [
  "client",
  "edge",
  "compute",
  "data",
  "storage",
  "messaging",
  "security",
  "observability",
] as const;

export function getComponentByType(type: string): ComponentDefinition | undefined {
  return COMPONENT_CATALOG.find((c) => c.type === type);
}

export function defaultAttributes(
  definition: ComponentDefinition
): Record<string, string | number | boolean> {
  return Object.fromEntries(
    definition.attributes.map((attr) => [attr.key, attr.defaultValue])
  );
}
