import type { ComponentDefinition } from "./types";

export const COMPONENT_CATALOG: ComponentDefinition[] = [
  // Clients
  {
    type: "mobile_client",
    label: "Mobile Client",
    category: "client",
    description: "iOS/Android app used by end users",
    color: "#38bdf8",
    icon: "smartphone",
    attributes: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: ["iOS", "Android", "Cross-platform"],
        defaultValue: "Cross-platform",
      },
      {
        key: "network",
        label: "Network",
        type: "select",
        options: ["4G", "5G", "WiFi", "Mixed"],
        defaultValue: "Mixed",
      },
      {
        key: "offlineSupport",
        label: "Offline support",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "web_client",
    label: "Web Client",
    category: "client",
    description: "Browser-based web application",
    color: "#38bdf8",
    icon: "monitor",
    attributes: [
      {
        key: "device",
        label: "Primary device",
        type: "select",
        options: ["Desktop", "Mobile", "Both"],
        defaultValue: "Both",
      },
      {
        key: "rendering",
        label: "Rendering",
        type: "select",
        options: ["CSR", "SSR", "SSG", "Hybrid"],
        defaultValue: "SSR",
      },
    ],
  },
  {
    type: "iot_device",
    label: "IoT Device",
    category: "client",
    description: "Sensor, camera, or embedded device",
    color: "#38bdf8",
    icon: "cpu",
    attributes: [
      {
        key: "protocol",
        label: "Protocol",
        type: "select",
        options: ["MQTT", "HTTP", "CoAP", "WebSocket"],
        defaultValue: "MQTT",
      },
      {
        key: "bandwidth",
        label: "Bandwidth",
        type: "select",
        options: ["Low", "Medium", "High"],
        defaultValue: "Low",
      },
    ],
  },

  // Edge
  {
    type: "dns",
    label: "DNS",
    category: "edge",
    description: "Domain name resolution and routing",
    color: "#a78bfa",
    icon: "globe",
    attributes: [
      {
        key: "routing",
        label: "Routing policy",
        type: "select",
        options: ["Simple", "Latency-based", "Geo", "Weighted"],
        defaultValue: "Latency-based",
      },
      {
        key: "ttlSeconds",
        label: "TTL",
        type: "number",
        min: 1,
        max: 86400,
        unit: "s",
        defaultValue: 60,
      },
    ],
  },
  {
    type: "cdn",
    label: "CDN",
    category: "edge",
    description: "Edge cache for static and dynamic content",
    color: "#a78bfa",
    icon: "globe-2",
    attributes: [
      {
        key: "regions",
        label: "Edge regions",
        type: "select",
        options: ["Single", "Multi-region", "Global"],
        defaultValue: "Global",
      },
      {
        key: "cacheTtl",
        label: "Cache TTL",
        type: "number",
        min: 0,
        max: 86400,
        unit: "s",
        defaultValue: 300,
      },
      {
        key: "httpsOnly",
        label: "HTTPS only",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "api_gateway",
    label: "API Gateway",
    category: "edge",
    description: "Entry point for APIs: routing, auth, throttling",
    color: "#a78bfa",
    icon: "door-open",
    attributes: [
      {
        key: "auth",
        label: "Auth",
        type: "select",
        options: ["None", "API Key", "JWT", "OAuth2"],
        defaultValue: "JWT",
      },
      {
        key: "rateLimitRps",
        label: "Rate limit",
        type: "number",
        min: 1,
        max: 1000000,
        unit: "rps",
        defaultValue: 1000,
      },
      {
        key: "timeoutMs",
        label: "Timeout",
        type: "number",
        min: 50,
        max: 60000,
        unit: "ms",
        defaultValue: 3000,
      },
    ],
  },
  {
    type: "load_balancer",
    label: "Load Balancer",
    category: "edge",
    description: "Distributes traffic across backends",
    color: "#a78bfa",
    icon: "scale",
    attributes: [
      {
        key: "layer",
        label: "Layer",
        type: "select",
        options: ["L4", "L7"],
        defaultValue: "L7",
      },
      {
        key: "algorithm",
        label: "Algorithm",
        type: "select",
        options: ["Round robin", "Least connections", "IP hash", "Weighted"],
        defaultValue: "Least connections",
      },
      {
        key: "healthChecks",
        label: "Health checks",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "multiAz",
        label: "Multi-AZ",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "rate_limiter",
    label: "Rate Limiter",
    category: "edge",
    description: "Protects services from overload and abuse",
    color: "#a78bfa",
    icon: "gauge",
    attributes: [
      {
        key: "strategy",
        label: "Strategy",
        type: "select",
        options: ["Token bucket", "Sliding window", "Fixed window", "Leaky bucket"],
        defaultValue: "Token bucket",
      },
      {
        key: "limitRps",
        label: "Limit",
        type: "number",
        min: 1,
        max: 1000000,
        unit: "rps",
        defaultValue: 100,
      },
      {
        key: "scope",
        label: "Scope",
        type: "select",
        options: ["Per IP", "Per user", "Global", "Per API key"],
        defaultValue: "Per user",
      },
    ],
  },
  {
    type: "waf",
    label: "WAF",
    category: "edge",
    description: "Web application firewall",
    color: "#a78bfa",
    icon: "shield",
    attributes: [
      {
        key: "mode",
        label: "Mode",
        type: "select",
        options: ["Detect", "Block"],
        defaultValue: "Block",
      },
      {
        key: "ddosProtection",
        label: "DDoS protection",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },

  // Compute
  {
    type: "app_server",
    label: "App Server",
    category: "compute",
    description: "Stateful or stateless application servers",
    color: "#34d399",
    icon: "server",
    attributes: [
      {
        key: "stateless",
        label: "Stateless",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 3,
      },
      {
        key: "autoScale",
        label: "Auto-scale",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "region",
        label: "Region strategy",
        type: "select",
        options: ["Single AZ", "Multi-AZ", "Multi-region"],
        defaultValue: "Multi-AZ",
      },
    ],
  },
  {
    type: "microservice",
    label: "Microservice",
    category: "compute",
    description: "Focused service for a domain capability",
    color: "#34d399",
    icon: "boxes",
    attributes: [
      {
        key: "name",
        label: "Service name",
        type: "text",
        defaultValue: "service",
      },
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 3,
      },
      {
        key: "timeoutMs",
        label: "Timeout",
        type: "number",
        min: 50,
        max: 60000,
        unit: "ms",
        defaultValue: 2000,
      },
    ],
  },
  {
    type: "serverless",
    label: "Serverless Function",
    category: "compute",
    description: "Event-driven function compute",
    color: "#34d399",
    icon: "zap",
    attributes: [
      {
        key: "runtime",
        label: "Runtime",
        type: "select",
        options: ["Node", "Python", "Go", "Java", "Other"],
        defaultValue: "Node",
      },
      {
        key: "memoryMb",
        label: "Memory",
        type: "number",
        min: 128,
        max: 10240,
        unit: "MB",
        defaultValue: 512,
      },
      {
        key: "timeoutMs",
        label: "Timeout",
        type: "number",
        min: 100,
        max: 900000,
        unit: "ms",
        defaultValue: 10000,
      },
      {
        key: "concurrency",
        label: "Max concurrency",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 100,
      },
    ],
  },
  {
    type: "worker",
    label: "Background Worker",
    category: "compute",
    description: "Async job processor / consumer",
    color: "#34d399",
    icon: "cog",
    attributes: [
      {
        key: "concurrency",
        label: "Concurrency",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 10,
      },
      {
        key: "retryPolicy",
        label: "Retries",
        type: "select",
        options: ["None", "3x", "5x", "Exponential backoff"],
        defaultValue: "Exponential backoff",
      },
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 2,
      },
    ],
  },
  {
    type: "batch_job",
    label: "Batch Job",
    category: "compute",
    description: "Scheduled or on-demand batch processing",
    color: "#34d399",
    icon: "calendar",
    attributes: [
      {
        key: "schedule",
        label: "Schedule",
        type: "select",
        options: ["On-demand", "Hourly", "Daily", "Weekly"],
        defaultValue: "Daily",
      },
      {
        key: "parallelism",
        label: "Parallelism",
        type: "number",
        min: 1,
        max: 1000,
        defaultValue: 4,
      },
    ],
  },

  // Data
  {
    type: "sql_database",
    label: "SQL Database",
    category: "data",
    description: "Relational database (Postgres, MySQL, etc.)",
    color: "#fbbf24",
    icon: "database",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["PostgreSQL", "MySQL", "SQL Server", "CockroachDB"],
        defaultValue: "PostgreSQL",
      },
      {
        key: "sizeGb",
        label: "Storage size",
        type: "number",
        min: 1,
        max: 1000000,
        unit: "GB",
        defaultValue: 100,
      },
      {
        key: "replication",
        label: "Replication",
        type: "select",
        options: ["None", "Async replicas", "Sync multi-AZ", "Multi-region"],
        defaultValue: "Async replicas",
      },
      {
        key: "sharding",
        label: "Sharding",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "shardKey",
        label: "Shard key",
        type: "select",
        options: ["None", "user_id", "tenant_id", "geo", "hash(id)", "range"],
        defaultValue: "None",
      },
      {
        key: "partitionStrategy",
        label: "Partition strategy",
        type: "select",
        options: ["None", "Hash", "Consistent hashing", "Range", "Directory"],
        defaultValue: "None",
      },
      {
        key: "shardCount",
        label: "Shard count",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 1,
      },
      {
        key: "readReplicas",
        label: "Read replicas",
        type: "number",
        min: 0,
        max: 100,
        defaultValue: 1,
      },
    ],
  },
  {
    type: "nosql_database",
    label: "NoSQL Database",
    category: "data",
    description: "Document, key-value, or wide-column store",
    color: "#fbbf24",
    icon: "database",
    attributes: [
      {
        key: "model",
        label: "Data model",
        type: "select",
        options: ["Document", "Key-value", "Wide-column", "Graph"],
        defaultValue: "Document",
      },
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["DynamoDB", "MongoDB", "Cassandra", "Redis", "Firestore", "Neo4j"],
        defaultValue: "DynamoDB",
      },
      {
        key: "sizeGb",
        label: "Storage size",
        type: "number",
        min: 1,
        max: 10000000,
        unit: "GB",
        defaultValue: 500,
      },
      {
        key: "consistency",
        label: "Consistency",
        type: "select",
        options: ["Eventual", "Strong", "Bounded staleness", "Session"],
        defaultValue: "Eventual",
      },
      {
        key: "partitioning",
        label: "Partitioning",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "partitionKey",
        label: "Partition key",
        type: "select",
        options: ["id", "user_id", "tenant_id", "geo+id", "composite"],
        defaultValue: "user_id",
      },
      {
        key: "hashing",
        label: "Hashing",
        type: "select",
        options: ["Modulo", "Consistent hashing", "Rendezvous", "Range"],
        defaultValue: "Consistent hashing",
      },
      {
        key: "globalTables",
        label: "Multi-region tables",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "cache",
    label: "Cache",
    category: "data",
    description: "In-memory cache for low-latency reads",
    color: "#fbbf24",
    icon: "layers",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["Redis", "Memcached", "CDN cache", "Application cache"],
        defaultValue: "Redis",
      },
      {
        key: "sizeGb",
        label: "Memory size",
        type: "number",
        min: 1,
        max: 10000,
        unit: "GB",
        defaultValue: 16,
      },
      {
        key: "ttlSeconds",
        label: "Default TTL",
        type: "number",
        min: 1,
        max: 86400,
        unit: "s",
        defaultValue: 300,
      },
      {
        key: "eviction",
        label: "Eviction",
        type: "select",
        options: ["LRU", "LFU", "TTL", "No eviction"],
        defaultValue: "LRU",
      },
      {
        key: "clustered",
        label: "Clustered",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "search_index",
    label: "Search Index",
    category: "data",
    description: "Full-text or vector search engine",
    color: "#fbbf24",
    icon: "search",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["Elasticsearch", "OpenSearch", "Algolia", "Typesense", "Vector DB"],
        defaultValue: "Elasticsearch",
      },
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 0,
        max: 20,
        defaultValue: 1,
      },
      {
        key: "shards",
        label: "Shards",
        type: "number",
        min: 1,
        max: 1000,
        defaultValue: 3,
      },
    ],
  },
  {
    type: "time_series_db",
    label: "Time-Series DB",
    category: "data",
    description: "Metrics and high-volume time series storage",
    color: "#fbbf24",
    icon: "activity",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["InfluxDB", "TimescaleDB", "Prometheus", "CloudWatch"],
        defaultValue: "TimescaleDB",
      },
      {
        key: "retentionDays",
        label: "Retention",
        type: "number",
        min: 1,
        max: 3650,
        unit: "days",
        defaultValue: 30,
      },
    ],
  },
  {
    type: "data_warehouse",
    label: "Data Warehouse",
    category: "data",
    description: "Analytics and OLAP warehouse",
    color: "#fbbf24",
    icon: "building-2",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["Snowflake", "BigQuery", "Redshift", "ClickHouse"],
        defaultValue: "BigQuery",
      },
      {
        key: "sizeTb",
        label: "Data size",
        type: "number",
        min: 1,
        max: 100000,
        unit: "TB",
        defaultValue: 10,
      },
    ],
  },

  // Storage
  {
    type: "object_storage",
    label: "Object Storage",
    category: "storage",
    description: "Blob/object store for media and files",
    color: "#fb923c",
    icon: "hard-drive",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["S3", "GCS", "Azure Blob", "MinIO"],
        defaultValue: "S3",
      },
      {
        key: "sizeTb",
        label: "Capacity",
        type: "number",
        min: 1,
        max: 1000000,
        unit: "TB",
        defaultValue: 50,
      },
      {
        key: "durability",
        label: "Durability",
        type: "select",
        options: ["11 nines", "99.999999999%", "Regional", "Cross-region"],
        defaultValue: "11 nines",
      },
      {
        key: "replication",
        label: "Replication",
        type: "select",
        options: ["Single region", "Cross-region", "Multi-region"],
        defaultValue: "Cross-region",
      },
    ],
  },
  {
    type: "block_storage",
    label: "Block Storage",
    category: "storage",
    description: "Persistent block volumes for VMs/containers",
    color: "#fb923c",
    icon: "disc",
    attributes: [
      {
        key: "iops",
        label: "IOPS",
        type: "number",
        min: 100,
        max: 1000000,
        defaultValue: 3000,
      },
      {
        key: "sizeGb",
        label: "Size",
        type: "number",
        min: 1,
        max: 100000,
        unit: "GB",
        defaultValue: 500,
      },
      {
        key: "replicated",
        label: "Replicated",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },

  // Messaging
  {
    type: "message_queue",
    label: "Message Queue",
    category: "messaging",
    description: "Point-to-point async messaging",
    color: "#f472b6",
    icon: "list-ordered",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["SQS", "RabbitMQ", "ActiveMQ", "Azure Queue"],
        defaultValue: "SQS",
      },
      {
        key: "delivery",
        label: "Delivery",
        type: "select",
        options: ["At-least-once", "Exactly-once", "At-most-once"],
        defaultValue: "At-least-once",
      },
      {
        key: "dlq",
        label: "Dead-letter queue",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "visibilityTimeoutSec",
        label: "Visibility timeout",
        type: "number",
        min: 1,
        max: 43200,
        unit: "s",
        defaultValue: 30,
      },
    ],
  },
  {
    type: "pubsub",
    label: "Pub/Sub",
    category: "messaging",
    description: "Publish-subscribe event fan-out",
    color: "#f472b6",
    icon: "radio",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["SNS", "Google Pub/Sub", "Redis Pub/Sub", "NATS"],
        defaultValue: "SNS",
      },
      {
        key: "fanout",
        label: "Fan-out style",
        type: "select",
        options: ["Push", "Pull", "Both"],
        defaultValue: "Push",
      },
      {
        key: "ordering",
        label: "Message ordering",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "stream_processor",
    label: "Stream Processor",
    category: "messaging",
    description: "Real-time event streaming platform",
    color: "#f472b6",
    icon: "waves",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["Kafka", "Kinesis", "Pulsar", "Redpanda"],
        defaultValue: "Kafka",
      },
      {
        key: "partitions",
        label: "Partitions",
        type: "number",
        min: 1,
        max: 10000,
        defaultValue: 12,
      },
      {
        key: "retentionHours",
        label: "Retention",
        type: "number",
        min: 1,
        max: 8760,
        unit: "h",
        defaultValue: 168,
      },
      {
        key: "replicationFactor",
        label: "Replication factor",
        type: "number",
        min: 1,
        max: 10,
        defaultValue: 3,
      },
    ],
  },
  {
    type: "event_bus",
    label: "Event Bus",
    category: "messaging",
    description: "Domain event backbone for services",
    color: "#f472b6",
    icon: "git-branch",
    attributes: [
      {
        key: "style",
        label: "Style",
        type: "select",
        options: ["Choreography", "Orchestration", "Hybrid"],
        defaultValue: "Choreography",
      },
      {
        key: "schemaRegistry",
        label: "Schema registry",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },

  // Security
  {
    type: "auth_service",
    label: "Auth Service",
    category: "security",
    description: "Authentication and session management",
    color: "#ef4444",
    icon: "key",
    attributes: [
      {
        key: "methods",
        label: "Methods",
        type: "select",
        options: ["Password", "OAuth/OIDC", "SSO", "Passwordless", "MFA"],
        defaultValue: "OAuth/OIDC",
      },
      {
        key: "tokenTtlMin",
        label: "Token TTL",
        type: "number",
        min: 1,
        max: 10080,
        unit: "min",
        defaultValue: 60,
      },
      {
        key: "mfa",
        label: "MFA required",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "identity_provider",
    label: "Identity Provider",
    category: "security",
    description: "External IdP / SSO provider",
    color: "#ef4444",
    icon: "fingerprint",
    attributes: [
      {
        key: "protocol",
        label: "Protocol",
        type: "select",
        options: ["OIDC", "SAML", "LDAP"],
        defaultValue: "OIDC",
      },
      {
        key: "provider",
        label: "Provider",
        type: "select",
        options: ["Auth0", "Okta", "Cognito", "Azure AD", "Custom"],
        defaultValue: "Cognito",
      },
    ],
  },
  {
    type: "secrets_manager",
    label: "Secrets Manager",
    category: "security",
    description: "Secure storage for keys and secrets",
    color: "#ef4444",
    icon: "lock",
    attributes: [
      {
        key: "rotation",
        label: "Auto-rotation",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["AWS Secrets Manager", "Vault", "GCP Secret Manager"],
        defaultValue: "Vault",
      },
    ],
  },

  // Observability
  {
    type: "monitoring",
    label: "Monitoring",
    category: "observability",
    description: "Metrics, alerts, and dashboards",
    color: "#94a3b8",
    icon: "bar-chart-3",
    attributes: [
      {
        key: "stack",
        label: "Stack",
        type: "select",
        options: ["Prometheus+Grafana", "Datadog", "CloudWatch", "New Relic"],
        defaultValue: "Prometheus+Grafana",
      },
      {
        key: "alerting",
        label: "Alerting",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "logging",
    label: "Logging",
    category: "observability",
    description: "Centralized log aggregation",
    color: "#94a3b8",
    icon: "scroll-text",
    attributes: [
      {
        key: "stack",
        label: "Stack",
        type: "select",
        options: ["ELK", "Loki", "CloudWatch Logs", "Datadog"],
        defaultValue: "ELK",
      },
      {
        key: "retentionDays",
        label: "Retention",
        type: "number",
        min: 1,
        max: 3650,
        unit: "days",
        defaultValue: 30,
      },
    ],
  },
  {
    type: "tracing",
    label: "Distributed Tracing",
    category: "observability",
    description: "Request traces across services",
    color: "#94a3b8",
    icon: "git-merge",
    attributes: [
      {
        key: "stack",
        label: "Stack",
        type: "select",
        options: ["OpenTelemetry", "Jaeger", "Zipkin", "X-Ray"],
        defaultValue: "OpenTelemetry",
      },
      {
        key: "sampleRate",
        label: "Sample rate %",
        type: "number",
        min: 1,
        max: 100,
        unit: "%",
        defaultValue: 10,
      },
    ],
  },

  // —— Agentic AI (Andrew Ng–style agentic workflows) ——
  {
    type: "llm_model",
    label: "LLM / Model",
    category: "agent",
    description: "Foundation model endpoint the agent calls (choose model + cost/latency trade-offs)",
    color: "#c084fc",
    icon: "brain",
    attributes: [
      {
        key: "provider",
        label: "Provider",
        type: "select",
        options: ["SpaceXAI/xAI", "OpenAI", "Anthropic", "Google", "Open-source", "Router/multi"],
        defaultValue: "SpaceXAI/xAI",
      },
      {
        key: "model",
        label: "Model",
        type: "select",
        options: [
          "grok-4.5",
          "grok-4.3",
          "gpt-4.1",
          "gpt-4.1-mini",
          "claude-sonnet",
          "claude-opus",
          "gemini-pro",
          "llama-70b",
          "local-small",
        ],
        defaultValue: "grok-4.5",
      },
      {
        key: "temperature",
        label: "Temperature",
        type: "number",
        min: 0,
        max: 2,
        defaultValue: 0.2,
      },
      {
        key: "maxTokens",
        label: "Max output tokens",
        type: "number",
        min: 64,
        max: 128000,
        defaultValue: 4096,
      },
      {
        key: "contextWindow",
        label: "Context window",
        type: "select",
        options: ["8k", "32k", "128k", "200k", "1M"],
        defaultValue: "128k",
      },
      {
        key: "structuredOutput",
        label: "Structured output",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "agent",
    label: "Agent",
    category: "agent",
    description: "LLM loop that plans, calls tools, and reasons over tool results",
    color: "#c084fc",
    icon: "bot",
    attributes: [
      {
        key: "role",
        label: "Role",
        type: "select",
        options: [
          "General",
          "Researcher",
          "Coder",
          "Planner",
          "Critic/Reflector",
          "Router",
          "Specialist",
        ],
        defaultValue: "General",
      },
      {
        key: "maxSteps",
        label: "Max tool-loop steps",
        type: "number",
        min: 1,
        max: 100,
        defaultValue: 8,
      },
      {
        key: "pattern",
        label: "Pattern",
        type: "select",
        options: [
          "ReAct",
          "Plan-and-execute",
          "Reflection",
          "Tool-use only",
          "Supervisor worker",
        ],
        defaultValue: "ReAct",
      },
      {
        key: "memoryEnabled",
        label: "Uses memory",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "parallelToolCalls",
        label: "Parallel tool calls",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "multi_agent_team",
    label: "Multi-Agent Team",
    category: "agent",
    description: "Several specialized agents that collaborate or run in parallel",
    color: "#c084fc",
    icon: "users",
    attributes: [
      {
        key: "topology",
        label: "Topology",
        type: "select",
        options: [
          "Supervisor",
          "Peer swarm",
          "Pipeline",
          "Map-reduce parallel",
          "Hierarchical",
        ],
        defaultValue: "Supervisor",
      },
      {
        key: "agentCount",
        label: "Agent count",
        type: "number",
        min: 2,
        max: 50,
        defaultValue: 3,
      },
      {
        key: "parallelism",
        label: "Parallel workers",
        type: "number",
        min: 1,
        max: 50,
        defaultValue: 3,
      },
      {
        key: "handoffStyle",
        label: "Handoff",
        type: "select",
        options: ["Shared scratchpad", "Message bus", "Direct handoff", "Shared memory"],
        defaultValue: "Shared scratchpad",
      },
    ],
  },

  // Tools
  {
    type: "tool_web_search",
    label: "Web Search Tool",
    category: "tools",
    description: "Search the live web; results feed back into the agent loop",
    color: "#22d3ee",
    icon: "search",
    attributes: [
      {
        key: "provider",
        label: "Provider",
        type: "select",
        options: ["Serper", "Tavily", "Bing", "Google", "xAI web search", "Custom"],
        defaultValue: "Tavily",
      },
      {
        key: "maxResults",
        label: "Max results",
        type: "number",
        min: 1,
        max: 50,
        defaultValue: 5,
      },
      {
        key: "recency",
        label: "Recency bias",
        type: "select",
        options: ["Any", "Day", "Week", "Month", "Year"],
        defaultValue: "Any",
      },
      {
        key: "timeoutMs",
        label: "Timeout",
        type: "number",
        min: 500,
        max: 60000,
        unit: "ms",
        defaultValue: 8000,
      },
    ],
  },
  {
    type: "tool_rag",
    label: "RAG Retriever Tool",
    category: "tools",
    description: "Retrieve chunks from a knowledge base / vector index for the LLM",
    color: "#22d3ee",
    icon: "book-open",
    attributes: [
      {
        key: "topK",
        label: "Top-K",
        type: "number",
        min: 1,
        max: 50,
        defaultValue: 5,
      },
      {
        key: "searchType",
        label: "Search type",
        type: "select",
        options: ["Dense vector", "Sparse/BM25", "Hybrid", "Graph RAG"],
        defaultValue: "Hybrid",
      },
      {
        key: "rerank",
        label: "Reranker",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "filters",
        label: "Metadata filters",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "tool_code_exec",
    label: "Code Executor Tool",
    category: "tools",
    description: "Sandboxed code execution for calculation, data transform, tests",
    color: "#22d3ee",
    icon: "terminal",
    attributes: [
      {
        key: "runtime",
        label: "Runtime",
        type: "select",
        options: ["Python", "JavaScript", "SQL", "Shell (restricted)"],
        defaultValue: "Python",
      },
      {
        key: "sandbox",
        label: "Sandbox",
        type: "select",
        options: ["Container", "WASM", "VM", "Remote notebook"],
        defaultValue: "Container",
      },
      {
        key: "timeoutSec",
        label: "Timeout",
        type: "number",
        min: 1,
        max: 600,
        unit: "s",
        defaultValue: 30,
      },
      {
        key: "networkAccess",
        label: "Network access",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "tool_function",
    label: "Function / API Tool",
    category: "tools",
    description: "Structured tool calling an internal or external API",
    color: "#22d3ee",
    icon: "wrench",
    attributes: [
      {
        key: "name",
        label: "Tool name",
        type: "text",
        defaultValue: "api_tool",
      },
      {
        key: "auth",
        label: "Auth",
        type: "select",
        options: ["None", "API key", "OAuth", "Service identity"],
        defaultValue: "API key",
      },
      {
        key: "idempotent",
        label: "Idempotent",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "schemaValidated",
        label: "JSON schema validated",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "tool_browser",
    label: "Browser / Scraper Tool",
    category: "tools",
    description: "Fetch or interact with web pages for the agent",
    color: "#22d3ee",
    icon: "globe",
    attributes: [
      {
        key: "mode",
        label: "Mode",
        type: "select",
        options: ["Fetch HTML", "Headless browser", "Readability extract"],
        defaultValue: "Readability extract",
      },
      {
        key: "jsRender",
        label: "JS render",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "maxPages",
        label: "Max pages / call",
        type: "number",
        min: 1,
        max: 20,
        defaultValue: 1,
      },
    ],
  },

  // Memory / RAG infra
  {
    type: "vector_db",
    label: "Vector Database",
    category: "memory",
    description: "Embedding index for RAG and semantic memory",
    color: "#a3e635",
    icon: "box",
    attributes: [
      {
        key: "engine",
        label: "Engine",
        type: "select",
        options: ["Pinecone", "Weaviate", "pgvector", "Milvus", "Chroma", "Qdrant", "Elasticsearch"],
        defaultValue: "pgvector",
      },
      {
        key: "dimensions",
        label: "Embedding dims",
        type: "number",
        min: 64,
        max: 4096,
        defaultValue: 1536,
      },
      {
        key: "metric",
        label: "Distance metric",
        type: "select",
        options: ["Cosine", "Dot product", "Euclidean"],
        defaultValue: "Cosine",
      },
      {
        key: "sharding",
        label: "Sharded index",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 0,
        max: 10,
        defaultValue: 1,
      },
    ],
  },
  {
    type: "embedding_model",
    label: "Embedding Model",
    category: "memory",
    description: "Turns text/docs into vectors for retrieval",
    color: "#a3e635",
    icon: "binary",
    attributes: [
      {
        key: "model",
        label: "Model",
        type: "select",
        options: [
          "text-embedding-3-large",
          "text-embedding-3-small",
          "voyage-3",
          "nomic-embed",
          "custom",
        ],
        defaultValue: "text-embedding-3-small",
      },
      {
        key: "batchSize",
        label: "Batch size",
        type: "number",
        min: 1,
        max: 2048,
        defaultValue: 64,
      },
    ],
  },
  {
    type: "document_indexer",
    label: "Document Indexer",
    category: "memory",
    description: "Ingest, chunk, embed, and index documents for RAG",
    color: "#a3e635",
    icon: "file-stack",
    attributes: [
      {
        key: "chunkStrategy",
        label: "Chunk strategy",
        type: "select",
        options: ["Fixed size", "Recursive", "Semantic", "By heading", "Parent-child"],
        defaultValue: "Recursive",
      },
      {
        key: "chunkSize",
        label: "Chunk size",
        type: "number",
        min: 64,
        max: 8000,
        unit: "tokens",
        defaultValue: 512,
      },
      {
        key: "overlap",
        label: "Overlap",
        type: "number",
        min: 0,
        max: 1000,
        unit: "tokens",
        defaultValue: 50,
      },
      {
        key: "schedule",
        label: "Refresh",
        type: "select",
        options: ["On upload", "Hourly", "Daily", "Streaming"],
        defaultValue: "On upload",
      },
    ],
  },
  {
    type: "agent_memory",
    label: "Agent Memory",
    category: "memory",
    description: "Short-term scratchpad and/or long-term user/session memory",
    color: "#a3e635",
    icon: "brain-circuit",
    attributes: [
      {
        key: "scope",
        label: "Scope",
        type: "select",
        options: ["Turn", "Session", "User long-term", "Org knowledge"],
        defaultValue: "Session",
      },
      {
        key: "store",
        label: "Store",
        type: "select",
        options: ["In-process", "Redis", "Vector DB", "SQL", "Hybrid"],
        defaultValue: "Redis",
      },
      {
        key: "summarization",
        label: "Auto-summarize",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "knowledge_base",
    label: "Knowledge Base",
    category: "memory",
    description: "Curated corpus (docs, tickets, policies) backing RAG",
    color: "#a3e635",
    icon: "library",
    attributes: [
      {
        key: "sources",
        label: "Sources",
        type: "select",
        options: ["PDFs", "Confluence/Notion", "Tickets", "Code repos", "Mixed"],
        defaultValue: "Mixed",
      },
      {
        key: "sizeGb",
        label: "Corpus size",
        type: "number",
        min: 1,
        max: 100000,
        unit: "GB",
        defaultValue: 50,
      },
      {
        key: "accessControl",
        label: "ACL / tenancy",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },

  // Orchestration
  {
    type: "workflow_orchestrator",
    label: "Workflow Orchestrator",
    category: "orchestration",
    description: "Multi-step graph: LLM → tools → LLM feedback loops, branches, retries",
    color: "#f9a8d4",
    icon: "workflow",
    attributes: [
      {
        key: "style",
        label: "Style",
        type: "select",
        options: ["DAG graph", "State machine", "Event-driven", "LangGraph-style", "Temporal"],
        defaultValue: "DAG graph",
      },
      {
        key: "maxIterations",
        label: "Max loop iterations",
        type: "number",
        min: 1,
        max: 100,
        defaultValue: 10,
      },
      {
        key: "checkpointing",
        label: "Checkpointing",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "humanInLoop",
        label: "Human-in-the-loop gates",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "router_gateway",
    label: "Agent Router",
    category: "orchestration",
    description: "Routes requests to the right model, agent, or tool path",
    color: "#f9a8d4",
    icon: "git-branch",
    attributes: [
      {
        key: "strategy",
        label: "Strategy",
        type: "select",
        options: ["Rules", "Classifier LLM", "Embedding similarity", "Cost-aware"],
        defaultValue: "Classifier LLM",
      },
      {
        key: "fallbackModel",
        label: "Fallback model",
        type: "select",
        options: ["Same", "Smaller/cheaper", "Larger/smarter", "Human queue"],
        defaultValue: "Smaller/cheaper",
      },
    ],
  },
  {
    type: "parallel_fanout",
    label: "Parallel Fan-out",
    category: "orchestration",
    description: "Run multiple agents/tools concurrently, then merge results",
    color: "#f9a8d4",
    icon: "git-fork",
    attributes: [
      {
        key: "concurrency",
        label: "Max concurrency",
        type: "number",
        min: 1,
        max: 100,
        defaultValue: 4,
      },
      {
        key: "mergeStrategy",
        label: "Merge strategy",
        type: "select",
        options: ["Concatenate", "Vote/consensus", "LLM synthesize", "First success"],
        defaultValue: "LLM synthesize",
      },
      {
        key: "failPolicy",
        label: "Partial failure",
        type: "select",
        options: ["Fail all", "Best effort", "Quorum"],
        defaultValue: "Best effort",
      },
    ],
  },
  {
    type: "guardrails",
    label: "Guardrails",
    category: "orchestration",
    description: "Safety filters, PII redaction, policy checks on inputs/outputs",
    color: "#f9a8d4",
    icon: "shield-check",
    attributes: [
      {
        key: "inputFilter",
        label: "Input filter",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "outputFilter",
        label: "Output filter",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "toolAllowlist",
        label: "Tool allowlist",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "piiRedaction",
        label: "PII redaction",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "human_review",
    label: "Human Review Gate",
    category: "orchestration",
    description: "Pause workflow for human approval before irreversible actions",
    color: "#f9a8d4",
    icon: "user-check",
    attributes: [
      {
        key: "trigger",
        label: "Trigger",
        type: "select",
        options: ["Always", "Low confidence", "High risk actions", "Cost threshold"],
        defaultValue: "High risk actions",
      },
      {
        key: "slaMinutes",
        label: "Review SLA",
        type: "number",
        min: 1,
        max: 10080,
        unit: "min",
        defaultValue: 30,
      },
    ],
  },

  // Evals
  {
    type: "span_eval",
    label: "Span / Step Eval",
    category: "evals",
    description: "Evaluate individual agent steps (tool choice, retrieval quality, reasoning)",
    color: "#facc15",
    icon: "microscope",
    attributes: [
      {
        key: "metrics",
        label: "Primary metrics",
        type: "select",
        options: [
          "Tool correctness",
          "Retrieval precision@k",
          "Faithfulness",
          "Latency per step",
          "Mixed",
        ],
        defaultValue: "Mixed",
      },
      {
        key: "judge",
        label: "Judge",
        type: "select",
        options: ["LLM-as-judge", "Rules/heuristics", "Human labels", "Hybrid"],
        defaultValue: "LLM-as-judge",
      },
      {
        key: "sampleRate",
        label: "Sample rate %",
        type: "number",
        min: 1,
        max: 100,
        unit: "%",
        defaultValue: 10,
      },
    ],
  },
  {
    type: "e2e_eval",
    label: "E2E Task Eval",
    category: "evals",
    description: "End-to-end task success: golden sets, online evals, regression suites",
    color: "#facc15",
    icon: "clipboard-check",
    attributes: [
      {
        key: "dataset",
        label: "Dataset",
        type: "select",
        options: ["Golden set", "Synthetic", "Production sampled", "A/B"],
        defaultValue: "Golden set",
      },
      {
        key: "metrics",
        label: "Metrics",
        type: "select",
        options: [
          "Task success rate",
          "Answer quality",
          "Citation accuracy",
          "User thumbs",
          "Composite",
        ],
        defaultValue: "Task success rate",
      },
      {
        key: "cadence",
        label: "Cadence",
        type: "select",
        options: ["Per PR", "Nightly", "Continuous online", "Weekly"],
        defaultValue: "Nightly",
      },
      {
        key: "gateOnDeploy",
        label: "Deploy gate",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "trace_collector",
    label: "Agent Trace Collector",
    category: "evals",
    description: "Capture spans for prompts, tools, tokens, latency across the agent graph",
    color: "#facc15",
    icon: "waypoints",
    attributes: [
      {
        key: "backend",
        label: "Backend",
        type: "select",
        options: ["LangSmith", "Phoenix/Arize", "Langfuse", "OpenTelemetry", "Custom"],
        defaultValue: "OpenTelemetry",
      },
      {
        key: "storePrompts",
        label: "Store full prompts",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "piiScrub",
        label: "PII scrubbing",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "prompt_registry",
    label: "Prompt Registry",
    category: "evals",
    description: "Versioned prompts with rollout and eval comparison",
    color: "#facc15",
    icon: "notebook-pen",
    attributes: [
      {
        key: "versioning",
        label: "Versioning",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "abTesting",
        label: "A/B prompts",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  client: "Clients",
  edge: "Edge & Networking",
  compute: "Compute",
  data: "Data Stores",
  storage: "Storage",
  messaging: "Messaging & Streaming",
  security: "Security & Identity",
  observability: "Observability",
  agent: "Agents & Models",
  tools: "Tools",
  memory: "Memory & RAG",
  orchestration: "Orchestration",
  evals: "Evals & Tracing",
};

export const CATEGORY_ORDER = [
  "agent",
  "tools",
  "memory",
  "orchestration",
  "evals",
  "client",
  "edge",
  "compute",
  "data",
  "storage",
  "messaging",
  "security",
  "observability",
] as const;

export function getComponentByType(type: string): ComponentDefinition | undefined {
  return COMPONENT_CATALOG.find((c) => c.type === type);
}

export function defaultAttributes(
  definition: ComponentDefinition
): Record<string, string | number | boolean> {
  return Object.fromEntries(
    definition.attributes.map((attr) => [attr.key, attr.defaultValue])
  );
}
