import {
  Activity,
  BarChart3,
  Boxes,
  Building2,
  Calendar,
  Cog,
  Cpu,
  Database,
  Disc,
  DoorOpen,
  Fingerprint,
  Gauge,
  GitBranch,
  GitMerge,
  Globe,
  Globe2,
  HardDrive,
  Key,
  Layers,
  ListOrdered,
  Lock,
  Monitor,
  Radio,
  Scale,
  ScrollText,
  Search,
  Server,
  Shield,
  Smartphone,
  Waves,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  smartphone: Smartphone,
  monitor: Monitor,
  cpu: Cpu,
  globe: Globe,
  "globe-2": Globe2,
  "door-open": DoorOpen,
  scale: Scale,
  gauge: Gauge,
  shield: Shield,
  server: Server,
  boxes: Boxes,
  zap: Zap,
  cog: Cog,
  calendar: Calendar,
  database: Database,
  layers: Layers,
  search: Search,
  activity: Activity,
  "building-2": Building2,
  "hard-drive": HardDrive,
  disc: Disc,
  "list-ordered": ListOrdered,
  radio: Radio,
  waves: Waves,
  "git-branch": GitBranch,
  key: Key,
  fingerprint: Fingerprint,
  lock: Lock,
  "bar-chart-3": BarChart3,
  "scroll-text": ScrollText,
  "git-merge": GitMerge,
};

export function ComponentIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = ICONS[name] ?? Server;
  return <Icon className={className} />;
}
