import {
  Activity,
  BarChart3,
  Binary,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Brain,
  BrainCircuit,
  Building2,
  Calendar,
  ClipboardCheck,
  Cog,
  Cpu,
  Database,
  Disc,
  DoorOpen,
  FileStack,
  Fingerprint,
  Gauge,
  GitBranch,
  GitFork,
  GitMerge,
  Globe,
  Globe2,
  HardDrive,
  Key,
  Layers,
  Library,
  ListOrdered,
  Lock,
  Microscope,
  Monitor,
  NotebookPen,
  Radio,
  Scale,
  ScrollText,
  Search,
  Server,
  Shield,
  ShieldCheck,
  Smartphone,
  Terminal,
  UserCheck,
  Users,
  Waves,
  Waypoints,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  smartphone: Smartphone,
  monitor: Monitor,
  cpu: Cpu,
  globe: Globe,
  "globe-2": Globe2,
  "door-open": DoorOpen,
  scale: Scale,
  gauge: Gauge,
  shield: Shield,
  server: Server,
  boxes: Boxes,
  zap: Zap,
  cog: Cog,
  calendar: Calendar,
  database: Database,
  layers: Layers,
  search: Search,
  activity: Activity,
  "building-2": Building2,
  "hard-drive": HardDrive,
  disc: Disc,
  "list-ordered": ListOrdered,
  radio: Radio,
  waves: Waves,
  "git-branch": GitBranch,
  "git-fork": GitFork,
  key: Key,
  fingerprint: Fingerprint,
  lock: Lock,
  "bar-chart-3": BarChart3,
  "scroll-text": ScrollText,
  "git-merge": GitMerge,
  brain: Brain,
  bot: Bot,
  users: Users,
  "book-open": BookOpen,
  terminal: Terminal,
  wrench: Wrench,
  box: Box,
  binary: Binary,
  "file-stack": FileStack,
  "brain-circuit": BrainCircuit,
  library: Library,
  workflow: Workflow,
  "shield-check": ShieldCheck,
  "user-check": UserCheck,
  microscope: Microscope,
  "clipboard-check": ClipboardCheck,
  waypoints: Waypoints,
  "notebook-pen": NotebookPen,
};

export function ComponentIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = ICONS[name] ?? Server;
  return <Icon className={className} />;
}
